repos:
- repo: https://github.com/psf/black
  rev: 19.3b0
  hooks:
    - id: black
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: 'v0.720'
  hooks:
  - id: mypy
    args: [--ignore-missing-imports]

